### ISSUE TITLE
Anglais - Bulle en français dans donjon (wargs)

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversityPrivateBeta#14]
Alpha07
![20210425130429_1](https://user-images.githubusercontent.com/15092739/115994318-cd3f6380-a5d6-11eb-83db-891948adc91f.jpg)

**Comment by JulienNigon** [comment]
Pas de soucis, certaines traductions sont en cours. Tu peux ne pas remonter ce genre de cas.
