### ISSUE TITLE
Anglais - Event donjon non traduit (tous ceux de la naine)

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversityPrivateBeta#15]
Alpha07

![20210425130138_1](https://user-images.githubusercontent.com/15092739/115994359-f233d680-a5d6-11eb-90a8-47c022443260.jpg)
![20210425130148_1](https://user-images.githubusercontent.com/15092739/115994360-f2cc6d00-a5d6-11eb-8f81-575bac6547ac.jpg)
![20210425130226_1](https://user-images.githubusercontent.com/15092739/115994362-f2cc6d00-a5d6-11eb-82b7-9c6a0db4e433.jpg)
![20210425130259_1](https://user-images.githubusercontent.com/15092739/115994364-f3650380-a5d6-11eb-9f36-001abe9d6d43.jpg)

**Comment by JulienNigon** [comment]
Ok, c'est en cours, il manque une vague de traductions.
