### ISSUE TITLE
Anglais - Mise en forme de certaines magies manquante

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversityPrivateBeta#17]
Alpha07

Je pense que c'est pareil dans les autres langues mais j'ai pas vérifié...

Magie des runes & potions
![20210425122440_1](https://user-images.githubusercontent.com/15092739/115994468-5787c780-a5d7-11eb-948e-5105a1609aca.jpg)
![20210425124025_1](https://user-images.githubusercontent.com/15092739/115994460-48a11500-a5d7-11eb-81b9-464217175e17.jpg)
![20210425122250_1](https://user-images.githubusercontent.com/15092739/115994479-640c2000-a5d7-11eb-9fb5-8c4eba4be32d.jpg)
![20210425122249_1](https://user-images.githubusercontent.com/15092739/115994481-653d4d00-a5d7-11eb-9955-3ec21edadd5d.jpg)

Arcane mana a la bonne icône mais n'est pas en rose:
![20210425122235_1](https://user-images.githubusercontent.com/15092739/115994505-90c03780-a5d7-11eb-936b-d2610147ac36.jpg)
(pareil sur l'amulette arcanique mais j'ai perdu la capture d'écran)

**Comment by JulienNigon** [comment]
-Nature (l'école)
-Arcanes (l'ecole)
-Rune (Sous-magie)
-Potion (sous-magie

**Comment by JulienNigon** [comment]
J'ai commencé des correctifs, mais va falloir être vigilant

**Comment by Fouindor** [comment]
Pas de soucis, tu me diras quand tu voudras que je refasse une passe sur la version anglaise.
Je passerai ce que je vois sur le nouveau tracker.

**Comment by JulienNigon** [comment]
Top merci Axel ! Je te dirai.

**Comment by FlynFlykk** [comment]
Sword in the Stone --> Heroic
Cornucopia --> Nature
Green Dragon --> Nature
Shamanic Staff -->Nature
Plant that eats scholars'hands --> Health
Guild Banners -->Maj Adventurer
Village Banners -->Maj Peasant
Purple Dragon --> Arcane
Medical Bed -->Health
Magic ARmor -->Heath
Chil-eating bed --> "Sleeper's Soul"
Milliwing--> "Milliwing feather"
Alembic --> "Alcohol"
Rune Stone --> Rune
Medecine cabinet --> Health
Health-risk waffle maker -->Health
Infirmerie --> heal (le traducteur a retiré le mot health)
Potion workshop --> Potion skill
Rune Scriptoirum --> Rune skill
ElixirSylvestre --> Nature
FiltreDePouvoir -->Arcane
Fall season shoulder pads -->health
Arcane Amulet --> Arcane
Shamanic staff --> mana
