### ISSUE TITLE
Noms des Maisons qui peuvent dépasser

### ISSUE THREAD

**Issue by FlynFlykk** [JulienNigon/SpellcasterUniversityPrivateBeta#22]
On peut écrire des noms très longs pour les maisons. Peut être qu'on pourrait limiter la taille? Sinon je peux aussi modifier les bannières pour être sur 2 lignes. 
![image](https://user-images.githubusercontent.com/14259450/116056735-68d7df00-a67e-11eb-9913-4a62dcebac0d.png)
![image](https://user-images.githubusercontent.com/14259450/116056791-7725fb00-a67e-11eb-9842-87ed28d9c8de.png)

**Comment by JulienNigon** [comment]
On peut pas faire un texte ajustable ? Si c'est as top beau parce qu'ils ont mis un nom mega long ils s'en remettront

**Comment by FlynFlykk** [comment]
oki je vais voir si je peux laisse de la place pour écrire sur 2 lignes et je mettrai un auto size min tout petit si le texte est très long il sera très petit

**Comment by FlynFlykk** [comment]
fait
