### ISSUE TITLE
?Event d'Objectifs plus lisibles avec une étoile?

### ISSUE THREAD

**Issue by FlynFlykk** [JulienNigon/SpellcasterUniversityPrivateBeta#23]
Peut être qu'on pourrait mettre une étoile sur les évents qui donnent un objectif pour qu'ils soient plus visibles? Ou sur les réponses avec un atlas?
![image](https://user-images.githubusercontent.com/14259450/116057462-1d720080-a67f-11eb-8326-1a1d6231eab4.png)

**Comment by JulienNigon** [comment]
Semble être une bonne idée.
