### ISSUE TITLE
?New Splascreen?

### ISSUE THREAD

**Issue by FlynFlykk** [JulienNigon/SpellcasterUniversityPrivateBeta#34]
J'ai un peu regardé ce qui est fait, globalement c'est souvent sur fond noir, je peux voir si on veut mettre un petit cadre autour ou autre à réfléchir.

**Comment by JulienNigon** [comment]
Je te laisse gérer ça

**Comment by FlynFlykk** [comment]
ayé mis sur fond noir avec anim simple
