### ISSUE TITLE
Sélection Elèves

### ISSUE THREAD

**Issue by FlynFlykk** [JulienNigon/SpellcasterUniversityPrivateBeta#36]
Certains accessoires/ aberrations ne sont pas pris dans le contour bleu de sélection

**Comment by JulienNigon** [comment]
Une liste de ceux qui ont été repérés m'intéresse @FlynFlykk

**Comment by FlynFlykk** [comment]
Je vais les traquer 
![image](https://user-images.githubusercontent.com/14259450/116238841-30113600-a762-11eb-95ff-c0a4c62dc97e.png)
![image](https://user-images.githubusercontent.com/14259450/116238922-4f0fc800-a762-11eb-91d9-5c30af22e8cc.png)

**Comment by FlynFlykk** [comment]
![image](https://user-images.githubusercontent.com/14259450/116238719-07893c00-a762-11eb-915b-06f5c7ae8b31.png)

**Comment by FlynFlykk** [comment]
![image](https://user-images.githubusercontent.com/14259450/116239200-a9a92400-a762-11eb-9454-944511eb810d.png)
![image](https://user-images.githubusercontent.com/14259450/116239347-d3624b00-a762-11eb-800c-e795bbe46729.png)
![image](https://user-images.githubusercontent.com/14259450/116239646-30f69780-a763-11eb-9e31-0679906de332.png)
![image](https://user-images.githubusercontent.com/14259450/116240223-e1fd3200-a763-11eb-858f-7ce23d21b75e.png)
![image](https://user-images.githubusercontent.com/14259450/116240403-1244d080-a764-11eb-95e2-6ebe8a4f2373.png)

**Comment by FlynFlykk** [comment]
![image](https://user-images.githubusercontent.com/14259450/116243089-dcedb200-a766-11eb-80db-f0f14110a6aa.png)
![image](https://user-images.githubusercontent.com/14259450/116243180-f2fb7280-a766-11eb-82bd-f292bf92ed40.png)

**Comment by FlynFlykk** [comment]
Pour résumer :
-les cheveux des élèves humain et non humain
-les bouts de non humains (oreilles, cornes, queue de loup, museau de loup, crète de profond ....)
-Les aberrations (citrouille, tentacule, barbe, champignon....)
-les accessoires (ailes, épaulières...) 

Mais RAS sur les profs

**Comment by JulienNigon** [comment]
A tester avant de clore
