### ISSUE TITLE
Equipement et portrait

### ISSUE THREAD

**Issue by FlynFlykk** [JulienNigon/SpellcasterUniversityPrivateBeta#53]
![image](https://user-images.githubusercontent.com/14259450/116531604-a6877280-a8df-11eb-8a74-666cc6eef375.png)
Les elèves n'affichent pas leur accessoires, mais en même temps je pense qu'il doit manquer quelques version 2D. Je peux les faire si besoin ça ne sera pas long.

**Comment by FlynFlykk** [comment]
![image](https://user-images.githubusercontent.com/14259450/116549917-5e277f00-a8f6-11eb-86ec-0837386a369d.png)
J'ai ajouté les 3 équipements 2D qui manquaient (c'était ceux des non humains)

**Comment by JulienNigon** [comment]
En attente des tests

**Comment by FlynFlykk** [comment]
ALors apres test :

-la barbe ne s'affiche plus ici et aussi la tentacule, mais en generale les abérations s'affichent on dirait que c'est le cumul qui pose problème
![image](https://user-images.githubusercontent.com/14259450/118261635-20108a80-b4b4-11eb-96dd-a201a9272a1d.png)
![image](https://user-images.githubusercontent.com/14259450/118259671-b7281300-b4b1-11eb-9a8d-18bd2f1185ab.png)
-l'auréole et la couronne de fleur s'affichent partout sauf sur l'avenir (mais c'est presque pas grave comme il a son chapeau de diplomé)
-les cornes ne s'affiche nul part 2D
![image](https://user-images.githubusercontent.com/14259450/118261282-a082bb80-b4b3-11eb-9700-d00e983f6349.png)
L'amulette arcanique ne s'affiche nul part en 2D
![image](https://user-images.githubusercontent.com/14259450/118264082-73d0a300-b4b7-11eb-90ba-1c1ef71321d7.png)
-dent de loup ne s'affiche pas nul par en 2D
![image](https://user-images.githubusercontent.com/14259450/118259119-0d488680-b4b1-11eb-8376-d278ed0a50df.png)


Le reste semble fonctionner (check dans fiche eleves/classes/avenir et donjon) je vais surveiller sur les nons humains si je vois un soucis

**Comment by FlynFlykk** [comment]
Les equipements posent effectivement problemes avec les profonds ils en perdent leurs oreilles 
![image](https://user-images.githubusercontent.com/14259450/118288483-c8364b80-b4d4-11eb-8c56-973f463ac55f.png)

**Comment by FlynFlykk** [comment]
![image](https://user-images.githubusercontent.com/14259450/118288701-f156dc00-b4d4-11eb-81ee-080549b4c510.png)

normalement ils ont cette tete

**Comment by FlynFlykk** [comment]
![Uploading image.png…]()
