### ISSUE TITLE
Les objets du bureau du directeur pointent a travers le réglement

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversityPrivateBeta#94]
Alpha 07

Grimoire & Objets des factions

![20210504194556_1](https://user-images.githubusercontent.com/15092739/117486088-7ab45e80-af69-11eb-89ae-290c52f0faec.jpg)
![20210505163934_1](https://user-images.githubusercontent.com/15092739/117486092-7b4cf500-af69-11eb-8c38-6e7528052e75.jpg)

**Comment by JulienNigon** [comment]
Done !
