### ISSUE TITLE
Event Chat Blanc

### ISSUE THREAD

**Issue by FlynFlykk** [JulienNigon/SpellcasterUniversityPrivateBeta#99]
![image](https://user-images.githubusercontent.com/14259450/117796964-d6c00100-b24f-11eb-8d60-7e1e6847cd4c.png)
Pour cet event on gagne la carte ChatBlanc ou chat du seigneur demon, comme je n'ai pas la carte j'ai mis la carte Chat en attendant. L'illustration du chat blanc ainsi que la texture a appliquer sur le chat pour qu'il devienne blanc existe je peux aussi creer un nouveau prefab de chat en dupliquant l'ancien.

![image](https://user-images.githubusercontent.com/14259450/117797360-36b6a780-b250-11eb-8f2d-8f2adc5cb4f4.png)

**Comment by JulienNigon** [comment]
Comme on a pas de texte ça va être juste un swap color avec même texte et même effet. On pourra raffiner sur une prochaine mise à jour si on veut.
